### ISSUE TITLE
Using the audio jack

### ISSUE THREAD

**Issue by gogl92** [cybercase/up2_hacking#1]
Hi, did you have an idea if using the jack audio this could work? have you tested just with bluetooth?

**Comment by cybercase** [comment]
Hi gogl92!
Sorry, I'm not sure what you mean by "jack audio". The UP2 band does not have any audio jack plug.
By the way, I've tested this just with bluetooth. Unfortunately both my UP2 devices broke, so I cannot verify if it's still working.

**Comment by gogl92** [comment]
I meant the other version with the jack plug, but I think it is the jawbone up24, I sill have one so Im looking if there is any way to pull out the data.

**Comment by cybercase** [comment]
Oh yes, now I remember that!
Unfortunately the UP24 and the UP2 are two very different devices, and the code in this repo is meant only for the UP2.
